### ISSUE TITLE
Repository Setup Checklist

### ISSUE THREAD

**Issue by petyosi** [Glue42/core#3]
The list is heavily inspired by the items present in [FDC3 blueprint project](https://github.com/finos/project-blueprint).

## README
- [x] Badges pointing to the build and to NPM
- [x] Summary on the project purpose and features, authors, enterprise versions, etc.
- [x] Getting Started
- [x] Documentation links
- [x] Roadmap
- [x] Contributing + DCO
- [x] Support
- [x] License

## Licensing (MIT)

- [x] Add LICENSE file to the root
- [x] Set the correct license in package.json 

## Contributing

- [x] Setup DCO Bot - https://github.com/apps/dco
- [x] Add CONTRIBUTING
- [x] Add issue templates, configure them correctly

We can start with the issue templates from

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

The three items here seem fine:
https://github.com/finos/project-blueprint/tree/master/.github/ISSUE_TEMPLATE

## Misc

- [x] Add CODE-OF-CONDUCT (replace dash with underscore)
